name: Create and Publish Docker Image

on: 
  workflow_call:
    inputs:
      name: 
        required: true
        type: string

jobs:
  do-it: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, ${{ inputs.name }}!"

